AllCops:
  TargetRubyVersion: 3.0

inherit_gem:
  rubocop-espago: sorbet.yml

Bundler/GemComment:
  Enabled: false

Style/Documentation:
  Enabled: false

Sorbet/RedundantExtendTSig:
  Enabled: false

Sorbet/ForbidTSig:
  Enabled: false
