# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `ExpoNotifier::Mapper::Base`.
# Please instead update this file by running `bin/tapioca dsl ExpoNotifier::Mapper::Base`.


class ExpoNotifier::Mapper::Base
  include ShaleAttributeMethods

  module ShaleAttributeMethods; end
end
